name: Second Workflow
on:
  repository_dispatch:
    types: [pr-build]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      
      - name: Run second workflow task
        run: echo "Second workflow has been triggered successfully!"