name: Second Workflow

on:
  workflow_dispatch:  # This workflow can only be triggered via workflow_dispatch

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run second workflow task
        run: echo "Second workflow has been triggered successfully!"