name: Trigger Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run some initial task
        run: echo "Initial workflow is running..."
      
      - name: Trigger second workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: pr-build
          client-payload: '{"ref": "${{ github.ref }}", "pr_number": "${{ github.event.pull_request.number }}"}'